language: cpp
os: linux
compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo ./installDeps.sh

matrix:
  include:
    - sudo: required
      dist: trusty
  env:
    - CMAKE_ARGS=""
    - CMAKE_ARGS="-DUSE_QT5=True"

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make